name: 'Extract JIRA Keys'
description: 'Extract JIRA issue keys from branch names, commit messages, and PR titles'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  filter:
    description: 'Where to extract keys from (pr, commit, branch, all)'
    required: true
outputs:
  jira-keys:
    description: 'Array of unique JIRA issue keys'
runs:
  using: 'node12'
  main: 'index.js'
