name: Extract JIRA keys
on: [push, pull_request]

jobs:
  extract_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run action
        id: jira_keys
        uses: ./.github/actions/extract-jira-keys
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print JIRA keys
        run: echo "JIRA keys: ${{ steps.jira_keys.outputs.jira-keys }}"
