name: Extract JIRA keys and Get JIRA Info
on: [push, pull_request]

jobs:
  extract_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run extract-jira-keys action
        id: jira_keys
        uses: ./.github/actions/extract-jira-keys
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filter: 'all' # Can be 'pr', 'commit', 'branch', or 'all'
      - name: Run extract-jira-info action
        id: jira_info
        uses: ./.github/actions/extract-jira-info
        with:
          jira-host: ${{ secrets.JIRA_HOST }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-keys: ${{ steps.jira_keys.outputs.jira-keys }}
        if: steps.jira_keys.outputs.jira-keys != ''
      - name: Print JIRA issues info
        run: |
          echo "JIRA issues info: ${{ steps.jira_info.outputs.issues-info }}"
        if: steps.jira_keys.outputs.jira-keys != ''
      - name: Append JIRA info to PR description
        run: node ./.github/actions/append-pr-description/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUES_INFO: ${{ steps.jira_info.outputs.issues-info }}
        if: github.event_name == 'pull_request' && steps.jira_keys.outputs.jira-keys != ''
