name: Extract JIRA keys
on: [push, pull_request]

jobs:
  extract_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run action
        id: jira_keys
        uses: ./.github/actions/git-jira-commits-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filter: 'all' # Can be 'pr', 'commit', 'branch', or 'all'
